platform :ios, '8.0'

target 'jw-wallet' do


#遮罩
pod 'MBProgressHUD', '~> 1.0.0'

# 下拉刷新
pod 'MJRefresh', '3.1.12'

# 模型与字典转换
pod 'MJExtension', '3.0.13'

# 集成与H5交互框架
pod 'WebViewJavascriptBridge', '6.0.3'

# 全屏手势返回
pod 'FDFullscreenPopGesture', '1.1'

# 二维码生成和扫描
pod 'SGQRCode', '~> 2.2.0'

# 轮播图
#pod 'SDCycleScrollView','~> 1.75'

#加载图片
pod 'SDWebImage', '~> 4.4.0'

#布局框架
pod 'Masonry', '~> 1.1.0'

#极光推送
pod 'JPush', '~> 3.0.9'

#极光分享
pod 'JShare', '~> 1.5.0'

#网络请求框架
pod 'AFNetworking', '~> 3.2.1'

#webSocket框架
pod 'SocketRocket'
#数据库二次封装
pod 'BGFMDB', '~> 2.0.10'

## Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#use_frameworks!
#pod 'CKMnemonic', '~> 0.1.7'
end
