platform :ios, '7.0'

target 'jw-wallet' do
    
#遮罩
pod 'MBProgressHUD', '~> 1.0.0'

# 下拉刷新
pod 'MJRefresh', '3.1.12'

# 模型与字典转换
pod 'MJExtension', '3.0.13'

# 集成与H5交互框架
pod 'WebViewJavascriptBridge', '6.0.3'

# 全屏手势返回
pod 'FDFullscreenPopGesture', '1.1'

# 二维码生成和扫描
pod 'SGQRCode', '~> 2.2.0'

# 轮播图
pod 'SDCycleScrollView','~> 1.75'

#加载图片
pod 'SDWebImage', '~> 4.4.0'

#布局框架
pod 'Masonry', '~> 1.1.0'
end
